parameters:
    logger.level.debug: 100
    logger.level.info: 200
    logger.level.notice: 250
    logger.level.warning: 300
    logger.level.error: 400
    logger.level.critical: 500
    logger.level.alert: 550
    logger.level.emergency: 600

services:
    logger.stream:
        class: Monolog\Handler\StreamHandler
        arguments: ['%log_path%', '%logger.level.info%']
        public: false

    logger:
        class: Monolog\Logger
        arguments: ['tower']
        calls:
            - ['pushHandler', ['@logger.stream']]

    command.deploy:
        class: Twr\Command\DeployCommand
        tags:
            - { name: command }

    command.config:
        class: Twr\Command\ConfigCommand
        tags:
            - { name: command }

    command.deploy_env:
        class: Twr\Command\Deploy\EnvCommand
        tags:
            - { name: command }

    macros_bag:
        class: Twr\ParameterBag\Macros

    envs_bag:
        class: Twr\ParameterBag\Environments

    childs_bag:
        class: Twr\ParameterBag\Childs

    command_resolver:
        class: Twr\CommandResolver
        calls:
            - [setMacros, ['@macros_bag']]

    exports_resolver:
        class: Twr\ExportsResolver
        calls:
            - [setEnvs, ['@envs_bag']]

    runner:
        class: Twr\CommandRunner
        calls:
            - [setLogger, ['@logger']]